### PR TITLE
Feature/header-logo

### PR DESCRIPTION
**Pull request by RPinkha**
## Describe your changes
Changed the header logo to an h1 element. 
Also fixed the z-index for the header so it appears above all other elements and fixed the padding once again.

## Issue ticket number and link
EES-29
https://tripleten-apiary.atlassian.net/browse/EES-29

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by XDRO — APPROVED** [review]
Everything looks good. Maybe not an issue for this component specifically, but it'd be nice to have a transition animation timer for the button component's hover effect.

**Review by tomershvueli — APPROVED** [review]
👍

**Comment by tomershvueli** [comment]
@RPinkha there's a conflict here, once resolved I can merge.

**Comment by RPinkha** [comment]
@tomershvueli pulled from main. No conflicts.

**Pull request merged**
